[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc="0.8.25"
optimizer = true
optimizer_runs = 2000

fs_permissions = [{ access = "read-write", path = "./deployed.json"}]

[rpc_endpoints]
sepolia="https://1rpc.io/sepolia"
base="https://1rpc.io/base"
polygon="https://1rpc.io/matic"
mantle="https://rpc.mantle.xyz"

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
