[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules'
]
evm_version = 'cancun'
solc="0.8.23"
optimizer = true
optimizer_runs = 2000

fs_permissions = [{ access = "read-write", path = "./deployed.json"}]

[rpc_endpoints]
sepolia="https://ethereum-sepolia-rpc.publicnode.com"
base="https://1rpc.io/base"
polygon="https://1rpc.io/matic"
mantle="https://rpc.mantle.xyz"
mantle_sepolia="https://rpc.sepolia.mantle.xyz"

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
